harentius_blog_api_article_upsert:
    path: /article/upsert
    methods: [POST]
    controller: Harentius\BlogBundle\API\ArticleController::upsert

harentius_blog_api_article_delete:
    path: /article/create-update
    methods: [DELETE]
    controller: Harentius\BlogBundle\API\ArticleController::delete