harentius_blog_api_article_upsert:
    path: /article/upsert
    methods: [POST]
    controller: Harentius\BlogBundle\API\ArticleController::upsert

harentius_blog_api_article_delete:
    path: /article/delete
    methods: [DELETE]
    controller: Harentius\BlogBundle\API\ArticleController::delete

harentius_blog_api_file_upload:
    path: /file/upload
    methods: [POST]
    controller: Harentius\BlogBundle\API\FileController::upload

harentius_blog_api_file_delete:
    path: /file/delete
    methods: [DELETE]
    controller: Harentius\BlogBundle\API\FileController::delete