harentius_blog_homepage:
    path: /
    defaults: { _controller: 'Harentius\BlogBundle\Controller\HomepageController' }

harentius_blog_category:
    path: /category/{slug}/
    defaults: { _controller: 'Harentius\BlogBundle\Controller\CategoryController' }
    requirements:
        slug: '.*'

harentius_blog_tag:
    path: /tag/{slug}/
    defaults: { _controller: 'Harentius\BlogBundle\Controller\TagController' }

harentius_blog_archive_year:
    path: /{year}/
    defaults: { _controller: 'Harentius\BlogBundle\Controller\ArchiveController' }
    requirements:
        year: '\d+'

harentius_blog_archive_month:
    path: /{year}/{month}/
    defaults: { _controller: 'Harentius\BlogBundle\Controller\ArchiveController' }
    requirements:
        year: '\d+'
        month: '\d+'

harentius_blog_show_default:
    path: /{slug}
    defaults: { _controller: 'Harentius\BlogBundle\Controller\ShowController' }

harentius_blog_rate:
    path: /like/{article}/{type}
    defaults: { _controller: 'Harentius\BlogBundle\Controller\RateController', type: 'like' }
    methods: [POST]
    requirements:
        type: like|dislike

harentius_blog_view_count:
    path: /view-count/{id}
    defaults: { _controller: 'Harentius\BlogBundle\Controller\ViewCountController' }
