services:
    # default configuration for services in *this* file
    _defaults:
        public: false

    Harentius\BlogBundle\Entity\ArticleRepository:
        factory: ['@doctrine.orm.entity_manager', getRepository]
        arguments: [ Harentius\BlogBundle\Entity\Article ]

    Harentius\BlogBundle\Entity\PageRepository:
        class: Harentius\BlogBundle\Entity\PageRepository
        factory: ['@doctrine.orm.entity_manager', getRepository]
        arguments: [ Harentius\BlogBundle\Entity\Page ]

    Harentius\BlogBundle\Entity\CategoryRepository:
        factory: ['@doctrine.orm.entity_manager', getRepository]
        arguments: [ Harentius\BlogBundle\Entity\Category ]

    Harentius\BlogBundle\Entity\TagRepository:
        factory: ['@doctrine.orm.entity_manager', getRepository]
        arguments: [ Harentius\BlogBundle\Entity\Tag ]

    Harentius\BlogBundle\Entity\SettingRepository:
        factory: ['@doctrine.orm.entity_manager', getRepository]
        arguments: [ Harentius\BlogBundle\Entity\Setting ]

    Harentius\BlogBundle\Entity\AbstractPostRepository:
        factory: ['@doctrine.orm.entity_manager', getRepository]
        arguments: [ Harentius\BlogBundle\Entity\AbstractPost ]

    Harentius\BlogBundle\Entity\ApiKeyRepository:
        factory: ['@doctrine.orm.entity_manager', getRepository]
        arguments: [ Harentius\BlogBundle\Entity\ApiKey ]
