imports:
    - { resource: 'admin/*' }
    - { resource: 'twig.yaml' }
    - { resource: 'controller.yaml' }
    - { resource: 'command.yaml' }
    - { resource: 'cache.yaml' }
    - { resource: 'repositories.yaml' }
    - { resource: 'sitemap.yaml' }

services:
    _defaults:
        public: false
        autowire: true

    Harentius\BlogBundle\Menu\MenuBuilder:
        arguments:
            $homepageSlug: '%harentius_blog.homepage.page_slug%'

    Harentius\BlogBundle\Menu\MenuTwigExtension:
        tags:
            - { name: twig.extension }

    harentius_blog.array_cache:
        class: Doctrine\Common\Cache\ArrayCache

    Harentius\BlogBundle\Sidebar\Tags:
        arguments:
            $sidebarTagsLimit: '%harentius_blog.sidebar.tags_limit%'
            $sidebarTagSizes: '%harentius_blog.sidebar.tag_sizes%'

    Harentius\BlogBundle\Homepage:
        arguments:
            $categorySlug: '%harentius_blog.homepage.feed.category%'
            $homepageSlug: '%harentius_blog.homepage.page_slug%'

    Harentius\BlogBundle\Rating:
        arguments:
            $cache: '@harentius_blog.rating_cache'

    Harentius\BlogBundle\FileManagement\FilePathResolver:
        arguments:
            $webDir: '%kernel.project_dir%/public'

    Harentius\BlogBundle\FileManagement\Image\ImageOptimizer:
        arguments:
            - '@liip_imagine.cache.manager'
            - '@liip_imagine.filter.manager'
            - '@liip_imagine.data.manager'
            - '@Harentius\BlogBundle\FileManagement\FilePathResolver'
            - '%harentius_blog.articles.image_previews_base_uri%'

    Harentius\BlogBundle\EventListener\AdminUserListener:
        arguments:
            - '@security.password_encoder'
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }

    Harentius\BlogBundle\Router\PublicationUrlGenerator:
        arguments:
            $primaryLocale: '%harentius_blog.primary_locale%'

    Harentius\BlogBundle\Paginator:
        arguments:
            $defaultPerPage: '%harentius_blog.list.posts_per_page%'

    Harentius\BlogBundle\Breadcrumbs\BreadCrumbsManager: ~
    Harentius\BlogBundle\Breadcrumbs\BreadcrumbsTwigExtension:
        tags:
            - { name: twig.extension }
    Harentius\BlogBundle\Twig\RatingExtension: ~
    Harentius\BlogBundle\ViewsCounter: ~
    Harentius\BlogBundle\Sidebar\Archive: ~
    Harentius\BlogBundle\FileManagement\FileManager: ~
