services:
    _defaults:
        public: false
        autowire: true

    Harentius\BlogBundle\Menu\MenuBuilder:
        arguments:
            $homepageSlug: '%harentius_blog.homepage.page_slug%'

    Harentius\BlogBundle\Menu\MenuTwigExtension:
        tags:
            - { name: twig.extension }

    Harentius\BlogBundle\Sidebar\Tags:
        arguments:
            $sidebarTagsLimit: '%harentius_blog.sidebar.tags_limit%'
            $sidebarTagSizes: '%harentius_blog.sidebar.tag_sizes%'

    Harentius\BlogBundle\Homepage:
        arguments:
            $categorySlug: '%harentius_blog.homepage.feed.category%'
            $homepageSlug: '%harentius_blog.homepage.page_slug%'

    Harentius\BlogBundle\Rating: ~

    Harentius\BlogBundle\Router\PublicationUrlGenerator:
        arguments:
            $primaryLocale: '%harentius_blog.primary_locale%'

    Harentius\BlogBundle\Paginator:
        arguments:
            $defaultPerPage: '%harentius_blog.list.posts_per_page%'

    Harentius\BlogBundle\Breadcrumbs\BreadCrumbsManager: ~
    Harentius\BlogBundle\Breadcrumbs\BreadcrumbsTwigExtension:
        tags:
            - { name: twig.extension }
    Harentius\BlogBundle\ViewsCounter: ~
    Harentius\BlogBundle\Sidebar\Archive: ~
