services:
    _defaults:
        public: false
        autowire: true
        tags:
            - { name: twig.extension }

   # Twig\Extensions\IntlExtension: ~
    Harentius\BlogBundle\Twig\PublicationUrlGeneratorExtension: ~
    Harentius\BlogBundle\Twig\SettingsExtension: ~
    Harentius\BlogBundle\Twig\ReadMoreExtension: ~
    Harentius\BlogBundle\Twig\RatingExtension: ~
