parameters:
    database_url: '%env(string:DATABASE_URL)%'

doctrine:
    dbal:
        server_version: '8.0.31'
        url: '%database_url%'
        charset: utf8mb4
        default_table_options:
            collate: utf8mb4_unicode_ci
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: 'doctrine.orm.naming_strategy.underscore_number_aware'
        auto_mapping: true
        dql:
            datetime_functions:
                year: 'DoctrineExtensions\Query\Mysql\Year'
                month: 'DoctrineExtensions\Query\Mysql\Month'
